services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hw02"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:567234@db:5432/hw02
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8000"

volumes:
  pgdata:
